In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('auto-mpg.csv')

In [ ]:
data.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320

In [ ]:
# type(data)

In [ ]:
data.tail(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [ ]:
data.shape

(398, 9)

In [ ]:
data.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [ ]:
data.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [ ]:
data['model year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [ ]:
data['model year'].value_counts()

model year
73    40
78    36
76    34
82    31
75    30
80    29
79    29
81    29
70    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

In [ ]:
cols_selected = ['weight','mpg']
small_data = data[cols_selected]

In [ ]:
small_data

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

In [ ]:
small_data.to_csv('small_data.csv')

In [ ]:
# !pip install openpyxl

In [ ]:
small_data.to_excel('small_data.xlsx')

In [ ]:
data.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [ ]:
data['kmpl'] = data['mpg']*0.42514370

In [ ]:
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kmpl
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,7.652587
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,6.377156
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,7.652587
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,6.802299
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,7.227443

In [ ]:
data = data.sort_values(by='kmpl',ascending=False)

In [ ]:
data.head(1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kmpl
322,46.6,4,86.0,65,2110,17.9,80,3,mazda glc,19.811696

In [ ]:
data.sort_values(by='weight')[['car name', 'weight']][:2]

          car name  weight
54     datsun 1200    1613
144  toyota corona    1649

In [ ]:
simple_data = {
    'col1': [1, 2, 3, 4],
    'col2': ['A', 'B', 'C', 'D']}
df = pd.DataFrame(simple_data, index=[2,7,8,1])

In [ ]:
df

   col1 col2
2     1    A
7     2    B
8     3    C
1     4    D

In [ ]:
df.loc[1] # loc gets the row corresponding to the index value passed

col1    4
col2    D
Name: 1, dtype: object

In [ ]:
df.iloc[1] #iloc gets the row corresponding to the positional value passed

col1    2
col2    B
Name: 7, dtype: object

In [ ]:
data.iloc[:2, :2]

      mpg  cylinders
322  46.6          4
329  44.6          4

In [ ]:
# rows 100 & 101, columns:1&2
data.iloc[100:102, 1:3]

     cylinders  displacement
197          4          90.0
141          4          98.0

In [ ]:
logical_expression = data['kmpl']<4.5
data[logical_expression]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kmpl
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250,4.251437
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20,4.251437
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d,3.826293

In [ ]:
boolean_expr = (data['kmpl']<20) & (data['model year']<80)

In [ ]:
data[boolean_expr]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kmpl
244,43.1,4,90.0,48,1985,21.5,78,2,volkswagen rabbit custom diesel,18.323693
247,39.4,4,85.0,70,2070,18.6,78,3,datsun b210 gx,16.750662
304,37.3,4,91.0,69,2130,14.7,79,2,fiat strada custom,15.857860
248,36.1,4,91.0,60,1800,16.4,78,3,honda civic cvcc,15.347688
245,36.1,4,98.0,66,1800,14.4,78,1,ford fiesta,15.347688
...,...,...,...,...,...,...,...,...,...,...
67,11.0,8,429.0,208,4633,11.0,72,1,mercury marquis,4.676581
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200,4.676581
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250,4.251437
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20,4.251437
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d,3.826293

In [ ]:
# find car from year 82 but with maximum weight
data[(data['model year']==82)].sort_values(by='weight',\
                                           ascending=False).iloc[0]\
                                            [['car name', 'weight']]

car name    amc concord dl
weight                3035
Name: 374, dtype: object

In [ ]:
g = data.groupby("model year")

In [ ]:
g.min()

,mpg,cylinders,displacement,horsepower,weight,acceleration,origin,car name,kmpl
model year,,,,,,,,,
70,9.0,4,97.0,113,1835,8.0,1,amc ambassador dpl,3.826293
71,12.0,4,71.0,100,1613,11.5,1,amc gremlin,5.101724
72,11.0,3,70.0,112,2100,11.0,1,amc ambassador sst,4.676581
73,11.0,3,68.0,100,1867,9.5,1,amc ambassador brougham,4.676581
74,13.0,4,71.0,100,1649,13.5,1,amc hornet,5.526868
75,13.0,4,90.0,100,1795,11.5,1,amc gremlin,5.526868
76,13.0,4,85.0,100,1795,12.0,1,amc hornet,5.526868
77,15.0,3,79.0,100,1825,11.1,1,bmw 320i,6.377156
78,16.2,4,78.0,100,1800,11.2,1,amc concord,6.887328
79,15.5,4,85.0,110,1915,11.3,1,amc concord dl 6,6.589727
80,19.1,3,70.0,100,1835,11.4,1,amc concord,8.120245
81,17.6,4,79.0,100,1755,12.6,1,buick century,7.482529
82,22.0,4,91.0,110,1965,11.6,1,amc concord dl,9.353161

In [ ]:
data

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,kmpl
322,46.6,4,86.0,65,2110,17.9,80,3,mazda glc,19.811696
329,44.6,4,91.0,67,1850,13.8,80,3,honda civic 1500 gl,18.961409
325,44.3,4,90.0,48,2085,21.7,80,2,vw rabbit c (diesel),18.833866
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup,18.706323
326,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel),18.451237
...,...,...,...,...,...,...,...,...,...,...
67,11.0,8,429.0,208,4633,11.0,72,1,mercury marquis,4.676581
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200,4.676581
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250,4.251437
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20,4.251437
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d,3.826293

In [ ]:
for idx, row in data.iterrows():
    print(idx, row['car name'])
    break

322 mazda glc

In [ ]:
data = data.drop(columns=['origin'])

In [ ]:
data = data.drop_duplicates()

In [ ]:
data.values

array([[46.6, 4, 86.0, ..., 80, 'mazda glc', 19.81169642],
       [44.6, 4, 91.0, ..., 80, 'honda civic 1500 gl', 18.96140902],
       [44.3, 4, 90.0, ..., 80, 'vw rabbit c (diesel)', 18.83386591],
       ...,
       [10.0, 8, 360.0, ..., 70, 'ford f250', 4.251437],
       [10.0, 8, 307.0, ..., 70, 'chevy c20', 4.251437],
       [9.0, 8, 304.0, ..., 70, 'hi 1200d', 3.8262933]], dtype=object)

In [ ]:
car_new = data.drop(["car name", 'kmpl'], axis=1)

In [ ]:
car_new

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year
322,46.6,4,86.0,65,2110,17.9,80
329,44.6,4,91.0,67,1850,13.8,80
325,44.3,4,90.0,48,2085,21.7,80
394,44.0,4,97.0,52,2130,24.6,82
326,43.4,4,90.0,48,2335,23.7,80
...,...,...,...,...,...,...,...
67,11.0,8,429.0,208,4633,11.0,72
27,11.0,8,318.0,210,4382,13.5,70
25,10.0,8,360.0,215,4615,14.0,70
26,10.0,8,307.0,200,4376,15.0,70
28,9.0,8,304.0,193,4732,18.5,70

In [ ]:
data[~(data['weight']>4000)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,car name,kmpl
322,46.6,4,86.0,65,2110,17.9,80,mazda glc,19.811696
329,44.6,4,91.0,67,1850,13.8,80,honda civic 1500 gl,18.961409
325,44.3,4,90.0,48,2085,21.7,80,vw rabbit c (diesel),18.833866
394,44.0,4,97.0,52,2130,24.6,82,vw pickup,18.706323
326,43.4,4,90.0,48,2335,23.7,80,vw dasher (diesel),18.451237
...,...,...,...,...,...,...,...,...,...
214,13.0,8,302.0,130,3870,15.0,76,ford f108,5.526868
208,13.0,8,318.0,150,3940,13.2,76,plymouth volare premier v8,5.526868
87,13.0,8,350.0,145,3988,13.0,73,chevrolet malibu,5.526868
96,13.0,8,360.0,175,3821,11.0,73,amc ambassador brougham,5.526868
124,11.0,8,350.0,180,3664,11.0,73,oldsmobile omega,4.676581

In [ ]:
us_weather = pd.DataFrame({
    "city": ["newyork", "chicago", "seatle"],
    "temperature": [21, 14, 35],
    "humidity": [68, 65, 75],
})

In [ ]:
india_weather = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 21, 35],
    "humidity": [60, 75, 78],
})

In [ ]:
us_weather

      city  temperature  humidity
0  newyork           21        68
1  chicago           14        65
2   seatle           35        75

In [ ]:
india_weather

       city  temperature  humidity
0    mumbai           32        60
1     delhi           21        75
2  banglore           35        78

In [ ]:
weather_us_india = pd.concat([india_weather, us_weather],\
                             ignore_index=True)

In [ ]:
weather_us_india

       city  temperature  humidity
0    mumbai           32        60
1     delhi           21        75
2  banglore           35        78
3   newyork           21        68
4   chicago           14        65
5    seatle           35        75

In [ ]:
pd.merge(india_weather, us_weather, on="temperature")

     city_x  temperature  humidity_x   city_y  humidity_y
0     delhi           21          75  newyork          68
1  banglore           35          78   seatle          75

In [ ]:
data = {'date': ['2023-09-15', '2023-09-16', '2023-09-17'],
        'value': [50, 75, 60]}
df = pd.DataFrame(data)

In [ ]:
df

         date  value
0  2023-09-15     50
1  2023-09-16     75
2  2023-09-17     60

In [ ]:
df['date'] = pd.to_datetime(df['date'])
print(df.dtypes)

date     datetime64[ns]
value             int64
dtype: object

In [ ]:
df['date'].dt.year>2023

0    False
1    False
2    False
Name: date, dtype: bool